remote_theme: pmarsceill/just-the-docs
logo: images/openaf_logo.png
favicon_ico: images/openaf.ico"
title: OpenAF docs
description: OpenAF guides, concepts and how-tos documentation.
eading_anchors: true
nav_sort: case_sensitive

ga_tracking: G-VC702B2LH6
ga_tracking_anonymize_ip: true
